name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'src/**'
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg portaudio19-dev
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Generate documentation
      run: |
        # Create docs directory
        mkdir -p docs
        
        # Copy README as markdown
        cp README.md docs/index.md
        
        # Test package import (with error handling)
        python -c "
        try:
            from webcam_security import SecurityMonitor, Config
            print('✅ Package imports successfully')
        except ImportError as e:
            print(f'⚠️  Import warning: {e}')
            print('✅ Documentation will be generated anyway')
        " || true
        
        # Create simple HTML documentation
        echo '<!DOCTYPE html>' > docs/index.html
        echo '<html><head><title>Webcam Security</title></head>' >> docs/index.html
        echo '<body><h1>Webcam Security Documentation</h1>' >> docs/index.html
        echo '<p>Install: <code>pip install webcam-security</code></p>' >> docs/index.html
        echo '<p>See <a href="https://github.com/JavierOramas/webcam-security">GitHub</a> for full documentation.</p>' >> docs/index.html
        echo '</body></html>' >> docs/index.html
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs 